# Generated by Django 3.2.7 on 2021-09-19 14:59

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210903_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='go.jpg', upload_to=blog.models.user_directory_path),
        ),
    ]
